# Where to go from here
This has been a supercharged introduction to statistics. Due to the rapid pace of the course some topics could not be discussed as thoroughly as they should have; some topics weren't discussed at all. Below is a list of a few courses that fill in those gaps. 

## I want to learn more about R programming:

* [R for beginners (MAS103M)](https://ugla.hi.is/kennsluskra/index.php?tab=nam&chapter=namskeid&id=70819320226&namskra=0)

* [R programming (MAS102M)](https://ugla.hi.is/kennsluskra/index.php?tab=nam&chapter=namskeid&id=70819220226&namskra=0)

## I want to take a deeper dive into the material but still keep it applied

* [Applied linear statistical models (STÆ312M)](https://ugla.hi.is/kennsluskra/index.php?tab=nam&chapter=namskeid&id=70819220226&namskra=0)

* [Biostatistics II (Clinical prediction models) (LÝÐ301F)](https://ugla.hi.is/kennsluskra/index.php?tab=nam&chapter=namskeid&id=02700520226&namskra=0)

## I want to learn about the other methods that are out there

* [Biostatistics III (Survival analysis) (LÝÐ079F)](https://ugla.hi.is/kennsluskra/index.php?tab=nam&chapter=namskeid&id=70762120230&namskra=0)

* [Mixed linear models (MAS104M)](https://ugla.hi.is/kennsluskra/index.php?tab=nam&chapter=namskeid&id=70867120226&namskra=0)

* [Applied data analysis (MAS202M)](https://ugla.hi.is/kennsluskra/index.php?tab=nam&chapter=namskeid&id=70819420230&namskra=0)

## I want to learn more about the underlying mathematics of the material we covered but in an accessible way

* [Computing and calculus for applied statistics (STÆ012F)](https://ugla.hi.is/kennsluskra/index.php?tab=nam&chapter=namskeid&id=70193820226&namskra=0)

* [Probability and statistics (MAS201F)](https://ugla.hi.is/kennsluskra/index.php?tab=nam&chapter=namskeid&id=70819420230&namskra=0)

Blabla
